config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "shops#index"
  resources :shops do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show]
  resources :shop_lists, only: [:index]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates_uniqueness_of :user_id, scope: :shop_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite_shop, only: [:create, :destroy]
  before_action :authenticate_user!

  def create
    if @shop.user_id == current_user.id
      @favorite = Favorite.create(user_id: current_user.id, shop_id: @shop.id)
      @favorite.save
    end
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, shop_id: @shop.id)
    @favorite.destroy
  end

  private

  def set_favorite_shop
    @shop = Shop.find(params[:shop_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user: current_user, shop_id: @shop.id) %>
    <%= link_to shop_favorites_path(@shop), method: :post, remote: true, class: "favorite-btn favorite-post" do %>
        <i class="fas fa-heart heart"></i>
    <% end %>
  <% else %>
    <%= link_to shop_favorites_path(@shop), method: :delete, remote: true, class: "favorite-btn favorite-delete" do %>
        <i class="fas fa-heart heart2"></i>
    <% end %>
<% end%>

app/views/favorites/create.js.erb
 $('#favorite_<%= @shop.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { shop: @shop }) %>");

app/views/favorites/destroy.js.erb
 $('#favorite_<%= @shop.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { shop: @shop }) %>");