config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "shops#index"
  resources :shops do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show]
  resources :shop_lists, only: [:index]
end

app/models/shop.rb
class Shop < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :image
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥a-zA-Z0-9ａ-ｚ０-９Ａ-Ｚ]+\z/, message: 'は登録出来ない値です' }
    validates :shop_url, format: { with: %r{http(s)?://([-\w]+\.)+[-\w]+(/[-\w./?%&=]*)?}, message: 'は登録出来ない値です' }
  end
  validates :genre_id, numericality: { other_than: 1 }

  def self.search(search)
    if search != ''
      Shop.where('name LIKE(?)', "%#{search}%")
    else
      Shop.all
    end
  end

  def previous
    user.shops.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    user.shops.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:show, :edit]

  def index
    @shops = Shop.all
    @shops = @shops.page(params[:page]).per(6)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.create(shop_params)
    if @shop.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to root_path
  end

  def search
    @shops = Shop.search(params[:keyword])
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :shop_url, :image, :genre_id).merge(user_id: current_user.id)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user.id == @shop.user_id
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_footer.html.erb
<div class= "footer-name">
  <p>My favorites.</p>
</div>

app/views/shops/_header.html.erb
<div class="top-header">
  <div class="text-image">
    <p>My favorites</p>
  </div>
</div>

app/views/shops/_header2.html.erb
<div class= "top-header2">
  <%= link_to "My favorites.", root_path, class: "title-page" %>
  <div class= btn-list>
    <li><%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: "my-page"%></li>
    <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete , class: "post1"%></li>
    <li><%= link_to "UPLOAD", new_shop_path, class: "post2"%></li>
  </div>
</div>

app/views/shops/_sample.html.erb
  <% if user_signed_in? %>
    <div class="grid-6">
      <div class="favorite-list">
        <p> -- Favorite List --</p>
      </div>
    </div>
  <% else %>
  <div class="grid-6">
    <%= link_to "LOGIN", new_user_session_path, class: "post"%>
    <%= link_to "SIGN UP", new_user_registration_path, class: "post"%>
    <p class="favorite-list"> -- Favorite List --</p>
  </div>
  <% end %>
<div class="sample-image">
    <div class="sample-image2">
      <p>sample brand1</p>
      <%= image_tag "sample.JPG", alt: "sample", id: "sample", class: "sample1" %>
      <div class="shops-name">
        <a class="shop-name">CLICKでURLへ！</a>
      </div>
    </div>
    <div class="sample-image2">
      <p>sample brand2</p>
      <%= image_tag "sample2.JPG", alt: "sample", id: "sample", class: "sample1" %>
      <div class="shops-name">
        <a class="shop-name">click the URL</a>
      </div>
    </div>
    <div class="sample-image2">
      <p>sample brand3</p>
      <%= image_tag "sample.JPG", alt: "sample", id: "sample", class: "sample1" %>
      <div class="shops-name">
        <a class="shop-name">click the URL</a>
      </div>
    </div>
    <div class="sample-image2">
      <p>sample brand4</p>
      <%= image_tag "sample2.JPG", alt: "sample", id: "sample", class: "sample1" %>
      <div class="shops-name">
        <a class="shop-name">click the URL</a>
      </div>
    </div>
</div>

app/views/shops/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>- Edit -</h2>
    <%= form_with(model: @shop, id: 'new_user', class: 'new_user', local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object%>
    <%# イメージ %>
      <div class="image-text">
        *イメージ画像
      </div>
    <div class="img-upload">
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, {id:"item-image", class: "file-form"} %>
      </div>
       <div id="image-preview"></div>
    </div>
    <%# イメージ %>
      <div class="field">
        *<%= f.label :genre_id %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>

      <div class="field">
        *<%= f.label :name %><br />
        <%= f.text_field :name, {class: "form"} %>
      </div>

      <div class="field">
        *<%= f.label :shop_url %><br />
        <%= f.text_field :shop_url, {class: "text-form"} %>
      </div>

      <div class="actions">
        <%= f.submit "アップデート", {class: "submit"}%>
      </div>
      
      <div class="attention-message">
        <p>「*」マークは必須項目になります。</p>
      </div>
    <% end %>
    <%= link_to "Back", shop_path(@shop.id), class: "user-back" %>
  </div>
</div>

app/views/shops/index.html.erb
<% if user_signed_in? %>
  <%= render "header2" %>
<% else %>
  <div class="wrapper">
    <%= render "header" %>
  </div>
<div class="title-all">
  <div class="title">
    <h1>-My favoritesとは-</h1>
    <p>自分のお気に入りのブランドをまとめられるサービスです...♡</p>
    <p>好きな画像にブランドのurlを登録して、自分好みのブランドまとめサイトが作れます</p>
  </div>
</div>
<% end %>
<main>
  <% if user_signed_in? && current_user.shops.length != 0 %>
      <p class="go">Myfavoritesへようこそ！</p>
      <div class="howto">
        <p>How to</p>
        <p>①uploadボタンから、好きなブランドを登録してね！</p>
        <p>②clickボタンを押すと、登録したURLのページへ飛ぶよ！</p>
        <p>③画像をクリックすると、登録した内容の確認ができるよ◎</p>
      </div>
    <div class="grid-6">
      <div class="favorite-list">
        <p> -- Favorite List --</p>
      </div>
    </div>
    <%= form_with(url: search_shops_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "ブランドを検索する", class: "search-input" %>
      <%= button_tag type: 'submit', class: 'search-btn' do%>
        検索<%= icon("fas", "search") %><% end%>
    <% end %>
    <div class="sample-image">
      <% @shops.each do |shop| %>
        <% if current_user.id == shop.user_id %>
        <div class="sample-image2">
          <% if shop.favorites.present? %>
            <div class="parent">
              <div class="like"></div>
              <p>like</p>
            </div>
          <% end %>
            <%= shop.name %>
            <br><%= link_to image_tag(shop.image, class: "sample1"), shop_path(shop.id)%>
          <div class="shops-name">
            <%= link_to "click the URL", shop.shop_url, class:"shop-name"%>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="side-icon">
      <p>UPLOAD!</p>
      <%= link_to image_tag("bear.png", class: "bear"),new_shop_path %>
    </div>
    <%= paginate(@shops) %>
    <%= link_to shop_lists_path, class:"shoplist-button" do %>
      <i class="fas fa-check"></i>my favoritesが用意したブランド一覧を見る
    <% end %>
  <% elsif user_signed_in? %>
    <p class="go">さぁ、Myfavoritesを始めてみよう！</p>
    <div class="howto">
      <p>How to</p>
      <p>①uploadボタンから、好きなブランドを登録してね！</p>
      <p>②clickボタンを押すと、登録したURLのページへ飛ぶよ！</p>
      <p>③画像をクリックすると、登録した内容の確認ができるよ◎</p>
    </div>
    <%= render "sample" %>
  <div class="side-icon">
    <p>UPLOAD!</p>
    <%= link_to image_tag("bear.png", class: "bear"),new_shop_path %>
  </div>
  <% else %>
    <%= render "sample" %>
  <% end %>
</main>
<div class="footer">
  <%= render "footer" %>
</div>

app/views/shops/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>- Up load -</h2>
    <%= form_with(model: @shop, id: 'new_user', class: 'new_user', local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object%>
    <%# イメージ %>
    <div class="image-text">
      *イメージ画像
    </div>
    <div class="img-upload">
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, {id:"item-image", class: "file-form"} %>
      </div>
      <div id="image-preview"></div>
    </div>
    <%# イメージ %>
      <div class="field">
        *<%= f.label :genre_id %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>
      
      <div class="field">
        *<%= f.label :name %><br />
        <%= f.text_field :name, {class: "form"} %>
      </div>

      <div class="field">
        *<%= f.label :shop_url %><br />
        <%= f.text_field :shop_url, {class: "text-form"} %>
      </div>

      <div class="actions">
        <%= f.submit "アップロード", {class: "submit"}%>
      </div>
      
      <div class="attention-message">
        <p>「*」マークは必須項目になります。</p>
      </div>
    <% end %>
    <%= link_to "Back", root_path, class: "user-back" %>
  </div>
</div>

app/views/shops/search.html.erb
<%= render "header2" %>

<main>
  <div class="grid-6">
      <div class="favorite-list1">
        <p> -- Favorite List --</p>
      </div>
      <%= link_to "profile", user_path(current_user.id), class: "my-page1"%>
    </div>
  <%= form_with(url: search_shops_path, local: true, method: :get, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "ブランドを検索する", class: "search-input" %>
      <%= button_tag type: 'submit', class: 'search-btn' do%>
      検索<%= icon("fas", "search") %><% end%>
    <p>-- 検索結果 --</p>
  <% end %>
  </div>
    <div class="sample-image">
      <% @shops.each do |shop| %>
        <% if current_user.id == shop.user_id %>
        <div class="sample-image2">
            <%= shop.name %>
            <br><%= link_to image_tag(shop.image, class: "sample1"), shop_path(shop.id)%>
          <div class="shops-name1">
            <%= link_to "click the URL", shop.shop_url, class:"shop-name"%>
          </div>
        </div>
        <% end %>
      <% end %>
      <div class="side-icon">
        <p>UPLOAD!</p>
        <%= link_to image_tag("bear.png", class: "bear"),new_shop_path %>
      </div>
    </div>
    <div class="back-page">
      <%= link_to 'トップページへ戻る', root_path , class:"back"%>
    </div>
</main>
<div class="footer">
  <%= render "footer" %>
</div>

app/views/shops/show.html.erb
<%= render "header2" %>
<main>
 <div class="main1">
  <div class="sample-image2">
    <div class="show-image">
      <%= image_tag @shop.image, class: 'sample2' %>
      <ul class="link-list">
        <li>
          <%= link_to 'EDIT', edit_shop_path, {method: :get, class: "link-text1"} %>
        </li>
        <li>
          <%= link_to 'DELETE', shop_path(@shop.id), {method: :delete, class: "link-text2"} %>
        </li>
        <div class="link-list2">
          <p class="link-name">Category</p>
          <p class="link-name2"><%= @shop.genre.name %></p>
          <p class="link-name">ShopName</p>
          <p class="link-name2"><%= @shop.name %></p>
          <p class="link-name">URL</p>
          <p class="link-name2"><%= @shop.shop_url %></p>
        </div>
        <div id="favorite_<%= @shop.id %>" class="favorite">
          <%= render partial: 'favorites/favorite', locals: { shop: @shop} %>
        </div>
        <div class="shop-next">
          <% if @shop.previous.present? %>
            <%= link_to shop_path(@shop.previous), {class: "shop-next"} do %>
              <i class="fas fa-angle-double-left"></i> 前へ
            <% end %>
          <% end %>
          <% if @shop.next.present? %>
            <%= link_to shop_path(@shop.next), {class: "shop-next"} do %>
              次へ <i class="fas fa-angle-double-right"></i>
            <% end %>
          <% end %>
        </div>
      </ul>
    </div>
  </div>
 </div>
</main>
<div class="footer">
  <%= render "footer" %>
</div>